# -*- coding: utf-8 -*-
"""file_handler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-9xIM_GLV03rsiQy4S3Tihd_Nhxlmh8
"""

import io
import fitz                       
from docx import Document        
from PIL import Image             
import pytesseract

def extract_text(file_bytes: bytes, file_name: str) -> str:
    """
    Extract text from a resume file (PDF or DOCX).
    For PDFs: use PyMuPDF, and if the stripped text is under a small threshold,
    fallback to OCR via pytesseract on each page.
    For DOCX: use python-docx to read paragraphs and tables.
    """
    ext = file_name.rsplit('.', 1)[-1].lower()

    if ext == 'pdf':
        pdf = fitz.open(stream=file_bytes, filetype='pdf')
        raw_text = ""
        for page in pdf:
            raw_text += page.get_text()

        if len(raw_text.strip()) < 50:  
            ocr_text = ""
            for page in pdf:
                pix = page.get_pixmap(dpi=200)
                img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
                ocr_text += ("\n" + pytesseract.image_to_string(img))
            raw_text = ocr_text

        pdf.close()
        return raw_text

    elif ext == 'docx':
        doc = Document(io.BytesIO(file_bytes))
        full_text = [para.text for para in doc.paragraphs]
        text = "\n".join(full_text)
        for table in doc.tables:
            for row in table.rows:
                cells = [cell.text for cell in row.cells if cell.text]
                if cells:
                    text += "\n" + " ".join(cells)
        return text

    else:
        raise ValueError(f"Unsupported file format: {ext}")